/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ChuckNorrisJoke {
        "firstName": string;
        "lastName": string;
    }
}
declare global {
    interface HTMLChuckNorrisJokeElement extends Components.ChuckNorrisJoke, HTMLStencilElement {
    }
    var HTMLChuckNorrisJokeElement: {
        prototype: HTMLChuckNorrisJokeElement;
        new (): HTMLChuckNorrisJokeElement;
    };
    interface HTMLElementTagNameMap {
        "chuck-norris-joke": HTMLChuckNorrisJokeElement;
    }
}
declare namespace LocalJSX {
    interface ChuckNorrisJoke {
        "firstName"?: string;
        "lastName"?: string;
    }
    interface IntrinsicElements {
        "chuck-norris-joke": ChuckNorrisJoke;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "chuck-norris-joke": LocalJSX.ChuckNorrisJoke & JSXBase.HTMLAttributes<HTMLChuckNorrisJokeElement>;
        }
    }
}
